### PR TITLE
Implement generate_figure_spinegeneric

### LINKED ISSUE #61: Make a figure for the spine-generic dataset
@jcohenadad will generate SNR and contrast results from the [spine-generic multicenter data](https://zenodo.org/record/4299140#.YQKcNlNKjaQ). The output will be a CSV like [this one](https://github.com/sct-pipeline/gm-challenge/releases/download/v0.1/results.csv).

We need a script that takes this CSV as input and generates a figure like this one:
Screen Shot 2021-07-29 at 8 15 47 AM

> Note: The figure above is only an illustration. At the end, there will be three distribution per xtick (not two, as in the figure above).

The library used to generate such plot is [RainCloudPlots](https://github.com/RainCloudPlots/RainCloudPlots#raincloud-plots).

The script will have to fetch the vendor (GE, Philips, Siemens) from the participants.tsv file of the spine-generic dataset. For inspiration, see [this script](https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/generate_figure.py)

Also, we need to figure out how to properly display the two y-axes (one for SNR one for contrast).

### PR DESCRIPTION
**Pull request by alexfoias**
Fixes https://github.com/sct-pipeline/gm-challenge/issues/61

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
you might want to add a `requirements.txt` file with seaborn, ptitprince and pandas.

**Review by jcohenadad — COMMENTED** [review]
I'm not sure if the code was already ready for trying, but i ran into this:

~~~
julien-macbook:~/code/gm-challenge $ python generate_figure_spinegeneric.py -ir /Users/julien/temp/gmchallenge_20210729_211000/results/results.csv -o bla
Traceback (most recent call last):
  File "/Users/julien/code/gm-challenge/generate_figure_spinegeneric.py", line 74, in <module>
    main(args.path_input_results, args.path_input_participants, args.path_output)
  File "/Users/julien/code/gm-challenge/generate_figure_spinegeneric.py", line 56, in main
    content_participants_tsv = pd.read_csv(path_input_participants, encoding="ISO-8859-1", sep="\t")
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/Users/julien/opt/miniconda3/lib/python3.9/site-packages/pandas/io/common.py", line 371, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>
~~~

using this file: [results.csv](https://github.com/sct-pipeline/gm-challenge/files/6904612/results.csv)

**Comment by alexfoias** [comment]
@jcohenadad I fixed it. :) Do you want to give it a try ?

**Comment by jcohenadad** [comment]
very nice @alexfoias !

can you pls remove as much blank space as possible:

Screen Shot 2021-07-30 at 1 47 04 PM

also, could you pls use change order and colors: GE (red), Philips (blue), Siemens (green). just to be consistent with our spine-generic project
thx!!!

**Comment by alexfoias** [comment]
@jcohenadad Let me know if you like the colors

**Comment by alexfoias** [comment]
In the last commit I also fixed the legend

**Comment by jcohenadad** [comment]
on 81fa741436e09d6f108d3a42cdd125a1517ab478:
- for the order can you pls do: GE, Philips, Siemens
- the figure is a biiiit to high, can you please squeeze it by let's say 50% vertically
- can you put less opacity so we can see the dots better
thanks!
- also, i find that the boxplots are _very_ close to each other, can you add a little bit of space between them?
- could you please also output the mean +/- std per manufacturer?

**Comment by alexfoias** [comment]
the spacing was done using https://github.com/mwaskom/seaborn/issues/1076#issuecomment-634541579

**Comment by alexfoias** [comment]
I'm looking for the mean and +/- std

**Comment by jcohenadad** [comment]
much better! but there is still room for improvement: there is white space available and the boxplots seem _very_ constrained -- could you please make them larger?

Screen Shot 2021-07-30 at 4 03 41 PM

Also, would it be possible to inverse the distributions and the box plots (swap them so the boxplots appear on the left)

also: philips needs to be blue (see https://github.com/sct-pipeline/gm-challenge/pull/62#issuecomment-890054850) and the boxplots order need to be consistant with the legend

**Comment by alexfoias** [comment]
I pushed some fixes

**Comment by jcohenadad** [comment]
Tried https://github.com/sct-pipeline/gm-challenge/pull/62/commits/48f9ea919d6d465346e77e2eb0ae58bde0a032f6

Syntax:
~~~
python generate_figure_spinegeneric.py -ip ~/code/spine-generic/data-multi-subject/participants.tsv -ir ~/temp/gmchallenge_20210729_211000_spinegeneric/results/results.csv -o bla5
~~~

Getting this:
figure_SNR_single

- There are still issues with the ordering. As mentioned in https://github.com/sct-pipeline/gm-challenge/pull/62#issuecomment-890099862 the order should be GE, Philips and Siemens. And most importantly the order should be the same in the legend and in the displayed boxplots.
- There is more white space in the left compared to the right, could you please center better?

**Review by jcohenadad — APPROVED** [review]

**Pull request merged**
