### PR TITLE
(WIP) Various fixes and implementations

### LINKED ISSUE #11: renaming of WMGM.py into process_data.py lost header comments
old function with header doc:
https://github.com/neuropoly/gm_challenge/blob/38897827db5ff73a7836f8e620f68f4d51ff5b54/WMGM.py

new renamed function without doc:
https://github.com/neuropoly/gm_challenge/blob/master/process_data.py

### LINKED ISSUE #18: SNR should be constant across contrasts
to fix by computing SNR inside WM (because it is constant)

### LINKED ISSUE #26: Refactor process_data.py to facilitate processing of phantom data
@stephaniealley what exactly do you have in mind for the refactoring?

### LINKED ISSUE #32: generate figures from phantom data
will require the following refactoring:
- adding metadata for each nii.gz phantom that indicates WM, GM, STD and smooth

### PR DESCRIPTION
**Pull request by jcohenadad**
Fixes #11, Fixes #26, Fixes #32, Fixes #18, Fixes, #19

### CODE REVIEW

**Comment by jcohenadad** [comment]
> The daemon requires the output to be packaged in a form that is not particularly useful otherwise 

Please write in the header of `WMGM` the exact input that is required: folder name, zip name, what files inside folder (with what names), etc.  Then, in the file `process_data.py` refer to the WMGM header, so everything is clear about inputs/outputs (not clear now).

**Comment by jcohenadad** [comment]
@stephaniealley if the current branch does not interfere with the challenge operations (ie people's submissions are processed and results sent back via WMGM script) then we should merge this branch and work on remaining issues in subsequent branches.

**Comment by stephaniealley** [comment]
@jcohenadad I am testing the branch now to make sure that everything will work. Once I have confirmed, I will let you know that we can merge.

**Comment by jcohenadad** [comment]
@stephaniealley: this PR is taking too long to be tested (it's been several days now) and people need to be able to reproduce their results from this repository (currently master is outdated). I will merge this PR now, and if you find issues with the WMGM communication script, open a specific issue about it.

**Comment by stephaniealley** [comment]
That makes sense. The specific problem is not related to this PR. I will open a separate issue.

**Pull request merged**
